### ISSUE TITLE
Database Missing

### ISSUE THREAD

**Issue by staneswilson** [Masterolic/Spotify-repo#17]
Database File is missing which raises error

**Comment by Masterolic** [comment]
Hello....can you show the error and also explain the issue a bit more please? Because we don't have database function here

**Comment by jejirehokumador** [comment]
Successfully tagged musicbot:latest
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/music/mbot/__main__.py", line 30, in <module>
    Mbot().run()
  File "/usr/local/lib/python3.8/site-packages/pyrogram/methods/utilities/run.py", line 80, in run
    run(self.start())
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/music/mbot/__init__.py", line 96, in start
    await super().start()
  File "/usr/local/lib/python3.8/site-packages/pyrogram/methods/utilities/start.py", line 58, in start
    is_authorized = await self.connect()
  File "/usr/local/lib/python3.8/site-packages/pyrogram/methods/auth/connect.py", line 40, in connect
    await self.load_session()
  File "/usr/local/lib/python3.8/site-packages/pyrogram/client.py", line 616, in load_session
    await self.storage.open()
  File "/usr/local/lib/python3.8/site-packages/pyrogram/storage/file_storage.py", line 58, in open
    self.conn = sqlite3.connect(str(path), timeout=1, check_same_thread=False)
sqlite3.OperationalError: unable to open database file

**Comment by Masterolic** [comment]
Ohh that was fixed re-clone your repo !...
